//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpUnits.Framework.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpUnits.Framework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot compare objects: {0}, {1}.
        /// </summary>
        internal static string CannotCompareObjects {
            get {
                return ResourceManager.GetString("CannotCompareObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find dimension {0}.
        /// </summary>
        internal static string CannotFindDimension {
            get {
                return ResourceManager.GetString("CannotFindDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set identifier more than once on element {0}: {1}.
        /// </summary>
        internal static string CannotSetIdentifierTwice {
            get {
                return ResourceManager.GetString("CannotSetIdentifierTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture {0} is already set for element {1}.
        /// </summary>
        internal static string CultureIsAlreadySet {
            get {
                return ResourceManager.GetString("CultureIsAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1}.
        /// </summary>
        internal static string DivisionOperation {
            get {
                return ResourceManager.GetString("DivisionOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate element name already exist: {0}.
        /// </summary>
        internal static string DuplicateElementNameAlreadyExist {
            get {
                return ResourceManager.GetString("DuplicateElementNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate symbols found: {0}.
        /// </summary>
        internal static string DuplicateSymbolsFound {
            get {
                return ResourceManager.GetString("DuplicateSymbolsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set {0} as default culture for element {2} because {1} already is.
        /// </summary>
        internal static string ElementAlreadyHaveDefaultCulture {
            get {
                return ResourceManager.GetString("ElementAlreadyHaveDefaultCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element {0} already use identifier {1}.
        /// </summary>
        internal static string ElementAlreadyUseIdentifier {
            get {
                return ResourceManager.GetString("ElementAlreadyUseIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element identifier not found: {0}.
        /// </summary>
        internal static string ElementIdentifierNotFound {
            get {
                return ResourceManager.GetString("ElementIdentifierNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element name must be a valid identifier: {0}.
        /// </summary>
        internal static string ElementNameMustBeValidIdentifier {
            get {
                return ResourceManager.GetString("ElementNameMustBeValidIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element name not found: {0}.
        /// </summary>
        internal static string ElementNameNotFound {
            get {
                return ResourceManager.GetString("ElementNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect format specifier: {0}.
        /// </summary>
        internal static string InvalidFormatSpecifier {
            get {
                return ResourceManager.GetString("InvalidFormatSpecifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal dimension {0} must have at least one derivation rule.
        /// </summary>
        internal static string MinimalDimensionMustHaveRule {
            get {
                return ResourceManager.GetString("MinimalDimensionMustHaveRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ×.
        /// </summary>
        internal static string MultiplicationSign {
            get {
                return ResourceManager.GetString("MultiplicationSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol of element is invalid : {0}.
        /// </summary>
        internal static string SymbolOfElementIsInvalid {
            get {
                return ResourceManager.GetString("SymbolOfElementIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}^{1}.
        /// </summary>
        internal static string ValueToThePowerOf {
            get {
                return ResourceManager.GetString("ValueToThePowerOf", resourceCulture);
            }
        }
    }
}
